### ISSUE TITLE
fade and scroll-fix effect 

### ISSUE THREAD

**Issue by tonyfrenzy** [chingu-coders/Voyage2-Owls-07#1]
Nice job, the background change to white and scroll-fix effect in the header not there yet.

Also, the "Sign In" tab is still touching up a little with other menus on smaller screen
![chingu header](https://user-images.githubusercontent.com/16845280/30929332-0f03515e-a3b6-11e7-8155-f4ce133a31f7.PNG)

**Comment by metazor** [comment]
Well done, this looks great. You can make a PR if you want Stefan to review too. I optimized for 880px only so far. I don't know how to create the header transition so I created a card for this issue on the Project Board. I don't see the need for separate logo.css. Why not put these rulesets into the styles.css? Also you use 4 spaces for indentation and I use 2 based on Google's styleguide: https://google.github.io/styleguide/htmlcssguide.html We should decide on a common coding style.

**Comment by tonyfrenzy** [comment]
Seperated the case so that after reviewing iy

**Comment by tonyfrenzy** [comment]
I seperated the css so that after reviewing it can be easily merged.

About the four spaces, I will fix all that. Tabs actually. 
I wanted to use 2spaces based on the resource you shared yesterday, it's still kind of hard for me to leave "tabing" behind yet.

**Comment by metazor** [comment]
Sure, no problem. Actually it's pretty easy to merge anyways, because you didn't modify the same lines.
